// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1PWLoSRpjWkGGR5s87nYcB0CQFt__70',
    appId: '1:676577793116:web:a6be7e9cfc87404110c299',
    messagingSenderId: '676577793116',
    projectId: 'reward-token-app',
    authDomain: 'reward-token-app.firebaseapp.com',
    storageBucket: 'reward-token-app.firebasestorage.app',
    measurementId: 'G-CQB9E748XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVVC3FuOxGv0xXa1Wc2GpuNSqw2CP2gd0',
    appId: '1:676577793116:android:cbbb1b3b3a98e23310c299',
    messagingSenderId: '676577793116',
    projectId: 'reward-token-app',
    storageBucket: 'reward-token-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFB4YkQjwLHz-vKz5Zv-6rQuEb1bK69Vk',
    appId: '1:676577793116:ios:dda60955944dd15f10c299',
    messagingSenderId: '676577793116',
    projectId: 'reward-token-app',
    storageBucket: 'reward-token-app.firebasestorage.app',
    iosBundleId: 'com.example.rewardTokenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFB4YkQjwLHz-vKz5Zv-6rQuEb1bK69Vk',
    appId: '1:676577793116:ios:dda60955944dd15f10c299',
    messagingSenderId: '676577793116',
    projectId: 'reward-token-app',
    storageBucket: 'reward-token-app.firebasestorage.app',
    iosBundleId: 'com.example.rewardTokenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa1PWLoSRpjWkGGR5s87nYcB0CQFt__70',
    appId: '1:676577793116:web:c0bcfeba1032021210c299',
    messagingSenderId: '676577793116',
    projectId: 'reward-token-app',
    authDomain: 'reward-token-app.firebaseapp.com',
    storageBucket: 'reward-token-app.firebasestorage.app',
    measurementId: 'G-CLFBDBSV0T',
  );
}
